export type formInputs = {
  logradouro: string;
  bairro: string;
  cidade: string;
  estado: string;
  cep: string;
  tipoImovel: "casa" | "apartamento" | "terreno" | "sobrado";
  locadorNome: string;
  locadorGenero: string;
  locadorCpf: string;
  locadorRg: string;
  locadorNacionalidade: string;
  locadorEstadoCivil: string;
  locadorProfissao: string;
  locadorEndereco: string;
  locadorBairro: string;
  locadorCidade: string;
  locadorCep: string;
  locatarioNome: string;
  locatarioGenero: string;
  locatarioCpf: string;
  locatarioRg: string;
  locatarioNacionalidade: string;
  locatarioEstadoCivil: string;
  locatarioProfissao: string;
  locatarioEndereco: string;
  locatarioBairro: string;
  locatarioCidade: string;
  locatarioEstado: string;
  locatarioCep: string;
  valorAluguel: string;
  vencimento: string;
  caucao: string;
  inicioContrato: string;
  fimContrato: string;
};
