export type formInputs = {
  logradouro: string;
  bairro: string;
  cidade: string;
  estado: string;
  cep: string;
  tipoImovel: "casa" | "apartamento" | "terreno" | "sobrado";
  locadorNome: string;
  locadorGenero: string;
  locadorDocumento: string;
  locadorNacionalidade: string;
  locadorEstadoCivil: string;
  locadorProfissao: string;
  locadorUf: string;
  locadorEndereco: string;
  locadorBairro: string;
  locadorCidade: string;
  locadorCep: string;
  locatarioNome: string;
  locatarioGenero: string;
  locatarioDocumento: string;
  locatarioNacionalidade: string;
  locatarioEstadoCivil: string;
  locatarioProfissao: string;
  locatarioEndereco: string;
  locatarioBairro: string;
  locatarioCidade: string;
  locatarioUf: string;
  locatarioCep: string;
  valorAluguel: string;
  vencimentoAluguel: string;
  caucao: string;
  inicioContrato: string;
  fimContrato: string;
};
