import type { Metadata } from "next";
import "./globals.css";
import { lato } from "@/app/ui/fonts";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Gerador de Contratos Alluguel Facil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`min-h-full flex flex-col ${lato.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
